// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3g2VVLGzlG6W0MCZ6TeN0150p9Suwlg',
    appId: '1:665405945291:web:83ef810b21e2af22a0b24e',
    messagingSenderId: '665405945291',
    projectId: 'ntc-totoro-pets',
    authDomain: 'ntc-totoro-pets.firebaseapp.com',
    storageBucket: 'ntc-totoro-pets.appspot.com',
    measurementId: 'G-ZGBBK4NYPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBobdFiLjT_T8AfrLpJUI_kDaJfXAmKPt4',
    appId: '1:665405945291:android:a335be223b000827a0b24e',
    messagingSenderId: '665405945291',
    projectId: 'ntc-totoro-pets',
    storageBucket: 'ntc-totoro-pets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVI2U0wDVOh6xc_y8eiL0HKuef7aG_As',
    appId: '1:665405945291:ios:1f9ef3aeb8648100a0b24e',
    messagingSenderId: '665405945291',
    projectId: 'ntc-totoro-pets',
    storageBucket: 'ntc-totoro-pets.appspot.com',
    iosBundleId: 'com.example.ntcTotoroPets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVI2U0wDVOh6xc_y8eiL0HKuef7aG_As',
    appId: '1:665405945291:ios:1f9ef3aeb8648100a0b24e',
    messagingSenderId: '665405945291',
    projectId: 'ntc-totoro-pets',
    storageBucket: 'ntc-totoro-pets.appspot.com',
    iosBundleId: 'com.example.ntcTotoroPets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3g2VVLGzlG6W0MCZ6TeN0150p9Suwlg',
    appId: '1:665405945291:web:b1932ca7d4c8e290a0b24e',
    messagingSenderId: '665405945291',
    projectId: 'ntc-totoro-pets',
    authDomain: 'ntc-totoro-pets.firebaseapp.com',
    storageBucket: 'ntc-totoro-pets.appspot.com',
    measurementId: 'G-0X3370N8WR',
  );
}
